In [1]:
import pandas as pd

df_diabetes = pd.read_csv('../data/diabetes.csv')
print("Shape:", df_diabetes.shape)
print("Columns:", df_diabetes.columns.tolist())
df_diabetes.head(3)

Shape: (13200, 11)
Columns: ['Country/Region/World', 'ISO', 'Sex', 'Year', 'Age', 'Prevalence of diabetes (18+ years)', 'Prevalence of diabetes (18+ years) lower 95% uncertainty interval', 'Prevalence of diabetes (18+ years) upper 95% uncertainty interval', 'Proportion of people with diabetes who were treated (30+ years)', 'Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval', 'Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval']

,Country/Region/World,ISO,Sex,Year,Age,Prevalence of diabetes (18+ years),Prevalence of diabetes (18+ years) lower 95% uncertainty interval,Prevalence of diabetes (18+ years) upper 95% uncertainty interval,Proportion of people with diabetes who were treated (30+ years),Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval,Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval
0,Afghanistan,AFG,Men,1990,Age-standardised,0.102185,0.043214,0.185308,0.234837,0.084755,0.464630
1,Afghanistan,AFG,Men,1991,Age-standardised,0.104102,0.044941,0.189061,0.234642,0.087199,0.457768
2,Afghanistan,AFG,Men,1992,Age-standardised,0.106136,0.046302,0.192939,0.234537,0.088188,0.451526

In [2]:
df_diabetes.info()

<class 'pandas.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                                                                                          Non-Null Count  Dtype
---  ------                                                                                          --------------  -----
 0   Country/Region/World                                                                            13200 non-null  str
 1   ISO                                                                                             13200 non-null  str
 2   Sex                                                                                             13200 non-null  str
 3   Year                                                                                            13200 non-null  int64
 4   Age                                                                                             13200 non-null  str
 5   Prevalence of diabetes (18+ years)                                                              13200 non-null  float64
 6   Prevalence of diabetes (18+ years) lower 95% uncertainty interval                               13200 non-null  float64
 7   Prevalence of diabetes (18+ years) upper 95% uncertainty interval                               13200 non-null  float64
 8   Proportion of people with diabetes who were treated (30+ years)                                 13200 non-null  float64
 9   Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval  13200 non-null  float64
 10  Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval  13200 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.1 MB

In [3]:
df_diabetes.describe()

,Year,Prevalence of diabetes (18+ years),Prevalence of diabetes (18+ years) lower 95% uncertainty interval,Prevalence of diabetes (18+ years) upper 95% uncertainty interval,Proportion of people with diabetes who were treated (30+ years),Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval,Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval
count,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000
mean,2006.000000,0.107940,0.065513,0.164859,0.350160,0.220796,0.499971
std,9.522265,0.062082,0.048878,0.082724,0.150868,0.141185,0.157643
min,1990.000000,0.017891,0.008627,0.025284,0.055726,0.015392,0.116278
25%,1998.000000,0.062965,0.030556,0.103312,0.218671,0.099065,0.373960
50%,2006.000000,0.087809,0.048712,0.145742,0.350943,0.198727,0.503856
75%,2014.000000,0.136183,0.084988,0.209246,0.464451,0.313030,0.620776
max,2022.000000,0.369129,0.296311,0.540125,0.860381,0.741505,0.945622

In [4]:
df_obesity = pd.read_csv('../data/obesity.csv')
print("Shape:", df_obesity.shape)
print("Columns:", df_obesity.columns.tolist())
df_obesity.head(3)

Shape: (6798, 4)
Columns: ['Entity', 'Code', 'Year', 'Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age']

,Entity,Code,Year,"Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+ years of age"
0,Afghanistan,AFG,1990,1.68080
1,Afghanistan,AFG,1991,1.81298
2,Afghanistan,AFG,1992,1.95725

In [5]:
print("Sex values:", df_diabetes['Sex'].unique())
print("Age values:", df_diabetes['Age'].unique())
print("Year range:", df_diabetes['Year'].min(), "~", df_diabetes['Year'].max())
print("Number of countries:", df_diabetes['Country/Region/World'].nunique())

Sex values: <StringArray>
['Men', 'Women']
Length: 2, dtype: str
Age values: <StringArray>
['Age-standardised']
Length: 1, dtype: str
Year range: 1990 ~ 2022
Number of countries: 200

In [6]:
df_diabetes = df_diabetes.rename(columns={
    'Country/Region/World': 'country',
    'ISO': 'iso',
    'Sex': 'sex',
    'Year': 'year',
    'Age': 'age',
    'Prevalence of diabetes (18+ years)': 'diabetes_prevalence',
    'Proportion of people with diabetes who were treated (30+ years)': 'treatment_rate'
})

df_obesity = df_obesity.rename(columns={
    'Entity': 'country',
    'Code': 'iso',
    'Year': 'year',
    'Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age': 'obesity_prevalence'
})

print("Diabetes columns:", df_diabetes.columns.tolist())
print("Obesity columns:", df_obesity.columns.tolist())

Diabetes columns: ['country', 'iso', 'sex', 'year', 'age', 'diabetes_prevalence', 'Prevalence of diabetes (18+ years) lower 95% uncertainty interval', 'Prevalence of diabetes (18+ years) upper 95% uncertainty interval', 'treatment_rate', 'Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval', 'Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval']
Obesity columns: ['country', 'iso', 'year', 'obesity_prevalence']

In [7]:
df_diabetes = df_diabetes.rename(columns={
    'Prevalence of diabetes (18+ years) lower 95% uncertainty interval': 'diabetes_lower_ci',
    'Prevalence of diabetes (18+ years) upper 95% uncertainty interval': 'diabetes_upper_ci',
    'Proportion of people with diabetes who were treated (30+ years) lower 95% uncertainty interval': 'treatment_lower_ci',
    'Proportion of people with diabetes who were treated (30+ years) upper 95% uncertainty interval': 'treatment_upper_ci'
})

print("All columns:", df_diabetes.columns.tolist())

All columns: ['country', 'iso', 'sex', 'year', 'age', 'diabetes_prevalence', 'diabetes_lower_ci', 'diabetes_upper_ci', 'treatment_rate', 'treatment_lower_ci', 'treatment_upper_ci']

In [8]:
nordic = ['Sweden', 'Norway', 'Denmark', 'Finland', 'Iceland', 'Netherlands']

# Filter Nordic countries, both sexes
df_nordic = df_diabetes[
    df_diabetes['country'].isin(nordic)
].copy()

print("Nordic rows:", df_nordic.shape)
print("\nRows per country:")
print(df_nordic.groupby(['country', 'sex'])['year'].count())
print("\nYear range:", df_nordic['year'].min(), "~", df_nordic['year'].max())

Nordic rows: (396, 11)

Rows per country:
country      sex
Denmark      Men      33
             Women    33
Finland      Men      33
             Women    33
Iceland      Men      33
             Women    33
Netherlands  Men      33
             Women    33
Norway       Men      33
             Women    33
Sweden       Men      33
             Women    33
Name: year, dtype: int64

Year range: 1990 ~ 2022